docker-compose: Make docker-compose/ docker compose commands compatible between old and new installation process #24150

diff --git a/bin/configure b/bin/configure
--- a/bin/configure
+++ b/bin/configure
@@ -14,6 +14,19 @@
 ###############################################################################
 set -euo pipefail
 
+if docker-compose --version > /dev/null 2>&1; then
+  echo 'Info: docker-compose found'
+  export DOCKER_COMMAND="docker-compose"
+elif docker compose version > /dev/null 2>&1; then
+  echo 'Info: docker compose plugin found' 
+  export DOCKER_COMMAND="docker compose"
+else
+  echo 'Error: Neither docker compose nor docker-compse was found, please install docker compose'
+  echo 'https://docs.docker.com/compose/install/linux/#install-using-the-repository'
+  exit 1
+fi
+echo "DOCKER_COMMAND=$DOCKER_COMMAND"
+
 export BASE_PATH=$(realpath "$(dirname $0)/..")
 . "${BASE_PATH}/bin/helpers/colors.sh"
 
@@ -239,7 +252,7 @@ activate_logging() {
     echo "" >> "$filename"
     echo "services:" >> "$filename"
     pwd
-    for service in $(docker-compose config | yq -M '.services | keys' | sed -e 's/^- *//'); do
+    for service in $(${DOCKER_COMMAND} config | yq -M '.services | keys' | sed -e 's/^- *//'); do
         echo "  $service:" >> "$filename"
         echo '    logging: *default-logging' >> "$filename"
     done
@@ -267,7 +280,7 @@ check_host_integration() {
         section "Enabling Host network integration"
 
         echo "services:" > "$filename"
-        for service in $(docker-compose config | yq -M '.services | keys' | sed -e 's/^- *//'); do
+        for service in $(${DOCKER_COMMAND} config | yq -M '.services | keys' | sed -e 's/^- *//'); do
             echo "  $service:" >> "$filename"
             echo "    extra_hosts:" >> "$filename"
             echo '      - "host.docker.internal:host-gateway"' >> "$filename"
diff --git a/bin/tools/uwsgi_stats b/bin/tools/uwsgi_stats
--- a/bin/tools/uwsgi_stats
+++ b/bin/tools/uwsgi_stats
@@ -3,6 +3,20 @@
 # Check the statistics for the backoffice server
 ###############################################################################
 set -euo pipefail
+
+if docker-compose --version > /dev/null 2>&1; then
+  echo 'Info: docker-compose found'
+  export DOCKER_COMMAND="docker-compose"
+elif docker compose version > /dev/null 2>&1; then
+  echo 'Info: docker compose plugin found' 
+  export DOCKER_COMMAND="docker compose"
+else
+  echo 'Error: Neither docker compose nor docker-compse was found, please install docker compose'
+  echo 'https://docs.docker.com/compose/install/linux/#install-using-the-repository'
+  exit 1
+fi
+echo "DOCKER_COMMAND=$DOCKER_COMMAND"
+
 BASE_PATH=`realpath "$(dirname $0)/../.."`
 
 stats_enabled=$(. $BASE_PATH/.env && echo $COOG_UWSGI_STATS)
@@ -12,10 +26,10 @@ if [[ "$stats_enabled" != "1" ]]; then
     exit 2
 fi
 
-coog_running=$(docker-compose ps --services | grep "^coog$" || true)
+coog_running=$(${DOCKER_COMMAND} ps --services | grep "^coog$" || true)
 if [[ ! "$coog_running" ]]; then
     echo Coog service is not running >&2
     exit 2
 fi
 
-docker-compose exec coog uwsgi --connect-and-read /tmp/uwsgi_stats
+${DOCKER_COMMAND} exec coog uwsgi --connect-and-read /tmp/uwsgi_stats
diff --git a/bin/up b/bin/up
--- a/bin/up
+++ b/bin/up
@@ -4,10 +4,23 @@
 ###############################################################################
 set -euo pipefail
 
+if docker-compose --version > /dev/null 2>&1; then
+  echo 'Info: docker-compose found'
+  export DOCKER_COMMAND="docker-compose"
+elif docker compose version > /dev/null 2>&1; then
+  echo 'Info: docker compose plugin found' 
+  export DOCKER_COMMAND="docker compose"
+else
+  echo 'Error: Neither docker compose nor docker-compse was found, please install docker compose'
+  echo 'https://docs.docker.com/compose/install/linux/#install-using-the-repository'
+  exit 1
+fi
+echo "DOCKER_COMMAND=$DOCKER_COMMAND"
+
 BASE_PATH=`realpath "$(dirname $0)/.."`
 . "${BASE_PATH}/bin/helpers/colors.sh"
 
 ${BASE_PATH}/bin/configure
 
 section "Starting up"
-docker-compose --env-file $BASE_PATH/.env up $@
+${DOCKER_COMMAND} --env-file $BASE_PATH/.env up $@
