manage_db: fix _wait_db function command issue
(cherry picked from commit bfcaba46f4953758830e08358d9ec7d50b2f7506)

diff --git a/bin/manage_db b/bin/manage_db
--- a/bin/manage_db
+++ b/bin/manage_db
@@ -6,7 +6,7 @@
 ###############################################################################
 set -euo pipefail
 
-BASE_PATH=`realpath "$(dirname $0)/.."`
+BASE_PATH=$(realpath "$(dirname $0)/..")
 . "${BASE_PATH}/bin/helpers/colors.sh"
 
 help() {
@@ -59,7 +59,7 @@ load() {
 
     format="${format:-sql}"
     if [[ "$format" = "zip" ]]; then
-        unzip -p "$dump_file" > /tmp/tmp_extracted_dump
+        unzip -p "$dump_file" >/tmp/tmp_extracted_dump
         format=sql
         dump_file=/tmp/tmp_extracted_dump
     fi
@@ -69,7 +69,7 @@ load() {
     if [[ "$format" = "sql" ]]; then
         docker-compose exec -- postgres \
             bash -c "cat /tmp/dump | psql -U $db_user -d $db_name" \
-            > /dev/null
+            >/dev/null
     else
         docker-compose exec -- postgres \
             pg_restore -U "$db_user" --no-owner --role "$db_user" -j 4 \
@@ -93,9 +93,9 @@ dump() {
     section "Dumping database $db_name to $dump_file (format $format)"
 
     if [[ "$format" = "sql" ]] || [[ "$format" = "zip" ]]; then
-        docker-compose exec -- postgres bash -c "pg_dump -U $db_user $db_name > /tmp/dump" > /dev/null
+        docker-compose exec -- postgres bash -c "pg_dump -U $db_user $db_name > /tmp/dump" >/dev/null
     else
-        docker-compose exec -- postgres pg_dump -U "$db_user" -d "$db_name" -Fc -Z5 -f /tmp/dump > /dev/null
+        docker-compose exec -- postgres pg_dump -U "$db_user" -d "$db_name" -Fc -Z5 -f /tmp/dump >/dev/null
     fi
     docker-compose cp postgres:/tmp/dump "$dump_file"
     docker-compose exec -- postgres rm "/tmp/dump"
@@ -115,7 +115,7 @@ update() {
 
     # We need to kill the "init" container because it may lead to deadlocks.
     # And we are updating the db anyaway
-    docker-compose rm -s -f init > /dev/null
+    docker-compose rm -s -f init >/dev/null
 
     if [[ "$#" = "0" ]]; then
         args=ir
@@ -134,7 +134,7 @@ change_admin_password() {
     # We need to kill the "init" container because it is started automatically,
     # and we do not need since the DB is supposed to already be up to date
     sleep 1
-    docker-compose rm -s -f init > /dev/null
+    docker-compose rm -s -f init >/dev/null
 
     docker-compose exec -- coog ep admin -d "$db_name" -p
 }
@@ -147,7 +147,6 @@ anonymize() {
         exit 1
     fi
     _start_services postgres
-
 
     docker-compose cp "$BASE_PATH/bin/resources/anonymize_coog_db.sql" postgres:/tmp/anonymize.sql
 
@@ -189,8 +188,8 @@ _load_configuration() {
     fi
 
     POSTGRES_HOST=$(. $BASE_PATH/.env && echo $POSTGRES_HOST)
-    [[ "$POSTGRES_HOST" = "postgres" ]] && USE_LOCAL_POSTGRES=1 \
-        || USE_LOCAL_POSTGRES=0
+    [[ "$POSTGRES_HOST" = "postgres" ]] && USE_LOCAL_POSTGRES=1 ||
+        USE_LOCAL_POSTGRES=0
 
     echo " "
 }
@@ -229,9 +228,9 @@ _restart() {
 _db_wait() {
     DB_RETRIES=20
 
-    until docker-compose exec -- pg_isready -U "$db_user" || [[ ${DB_RETRIES} -eq 0 ]]; do
+    until docker-compose exec -- postgres pg_isready -U "$db_user" || [[ ${DB_RETRIES} -eq 0 ]]; do
         echo "Waiting for postgres server, $((DB_RETRIES--)) remaining attempts..."
-        sleep 2;
+        sleep 2
     done
 }
 
@@ -240,65 +239,65 @@ shift
 
 while test $# -gt 0; do
     case "$1" in
-        --database)
-            shift
-            db_name=$1
-            shift
-            ;;
-        --format)
-            shift
-            format=$1
-            if [[ "$format" != "sql" ]] && [[ "$format" != "bin" ]] && [[ "$format" != "zip" ]]; then
-                echo "Invalid file format $format" >&2
-                help
-                exit 1
-            fi
-            shift
-            ;;
-        *)
-            break
-            ;;
+    --database)
+        shift
+        db_name=$1
+        shift
+        ;;
+    --format)
+        shift
+        format=$1
+        if [[ "$format" != "sql" ]] && [[ "$format" != "bin" ]] && [[ "$format" != "zip" ]]; then
+            echo "Invalid file format $format" >&2
+            help
+            exit 1
+        fi
+        shift
+        ;;
+    *)
+        break
+        ;;
     esac
 done
 
 case "$command" in
-    help)
-        help
-        exit 0
-        ;;
-    reset)
-        _load_configuration
-        _stop_everything
-        reset $*
-        _restart
-        ;;
-    load)
-        _load_configuration
-        _stop_everything
-        load $*
-        _restart
-        ;;
-    dump)
-        _load_configuration
-        dump $*
-        ;;
-    update)
-        _load_configuration
-        _stop_everything
-        update $*
-        _restart
-        ;;
-    change_admin_password)
-        _load_configuration
-        change_admin_password $*
-        ;;
-    anonymize)
-        _load_configuration
-        anonymize $*
-        ;;
-    *)
-        echo "Invalid action" >&2
-        help
-        exit 1
-        ;;
+help)
+    help
+    exit 0
+    ;;
+reset)
+    _load_configuration
+    _stop_everything
+    reset $*
+    _restart
+    ;;
+load)
+    _load_configuration
+    _stop_everything
+    load $*
+    _restart
+    ;;
+dump)
+    _load_configuration
+    dump $*
+    ;;
+update)
+    _load_configuration
+    _stop_everything
+    update $*
+    _restart
+    ;;
+change_admin_password)
+    _load_configuration
+    change_admin_password $*
+    ;;
+anonymize)
+    _load_configuration
+    anonymize $*
+    ;;
+*)
+    echo "Invalid action" >&2
+    help
+    exit 1
+    ;;
 esac
